export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import { Inter } from 'next/font/google'
import '../../../public/globals.css'
import '../../../public/css/bootstrap.min.css'
import '../../../public/css/common.css'
import '../../../public/css/home.css'
import '../../../public/css/responsive.css'
import '../../../public/css/inner_style.css'
import '../../../public/css/owl.theme.default.min.css'
import '../../../public/css/owl.carousel.css'
import '../../../public/css/base.css'
export default function ResultRootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
